update item set prime = "Yes", stock = "In stock" WHERE i_id = 1;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 2;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 3;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 4;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 5;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 6;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 7;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 8;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 9;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 10;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 11;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 12;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 13;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 14;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 15;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 16;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 17;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 18;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 19;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 20;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 21;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 22;
update item set prime = "Yes", stock = "Only 9 left in stock - order soon." WHERE i_id = 23;
update item set prime = "Yes", stock = "Only 9 left in stock - order soon." WHERE i_id = 24;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 25;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 26;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 27;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 28;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 29;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 30;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 31;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 32;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 33;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 34;
update item set prime = "No", stock = "In stock" WHERE i_id = 35;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 36;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 37;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 38;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 39;
update item set prime = "No", stock = "In stock" WHERE i_id = 40;
update item set prime = "No", stock = "In stock" WHERE i_id = 41;
update item set prime = "No", stock = "In stock" WHERE i_id = 42;
update item set prime = "No", stock = "In stock" WHERE i_id = 43;
update item set prime = "No", stock = "Only 3 left in stock - order soon." WHERE i_id = 44;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 45;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 46;
update item set prime = "No", stock = "In stock" WHERE i_id = 47;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 48;
update item set prime = "No", stock = "In stock" WHERE i_id = 49;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 50;
update item set prime = "No", stock = "In stock" WHERE i_id = 51;
update item set prime = "No", stock = "In stock" WHERE i_id = 52;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 53;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 54;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 55;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 56;
update item set prime = "No", stock = "In stock" WHERE i_id = 57;
update item set prime = "No", stock = "In stock" WHERE i_id = 58;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 59;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 60;
update item set prime = "No", stock = "Only 5 left in stock - order soon." WHERE i_id = 61;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 62;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 63;
update item set prime = "No", stock = "In stock" WHERE i_id = 64;
update item set prime = "Yes", stock = "Only 20 left in stock - order soon." WHERE i_id = 65;
update item set prime = "No", stock = "In stock" WHERE i_id = 66;
update item set prime = "No", stock = "In stock" WHERE i_id = 67;
update item set prime = "No", stock = "Only 15 left in stock - order soon." WHERE i_id = 68;
update item set prime = "No", stock = "In stock" WHERE i_id = 69;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 70;
update item set prime = "No", stock = "In stock" WHERE i_id = 71;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 72;
update item set prime = "Yes", stock = "Only 15 left in stock - order soon." WHERE i_id = 73;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 74;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 75;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 76;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 77;
update item set prime = "No", stock = "Only 6 left in stock - order soon." WHERE i_id = 78;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 79;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 80;
update item set prime = "No", stock = "In stock" WHERE i_id = 81;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 82;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 83;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 84;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 85;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 86;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 87;
update item set prime = "No", stock = "Only 2 left in stock - order soon." WHERE i_id = 88;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 89;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 90;
update item set prime = "No", stock = "In stock" WHERE i_id = 91;
update item set prime = "Yes", stock = "Only 19 left in stock - order soon." WHERE i_id = 92;
update item set prime = "No", stock = "In stock" WHERE i_id = 93;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 94;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 95;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 96;
update item set prime = "Yes", stock = "Only 19 left in stock - order soon." WHERE i_id = 97;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 98;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 99;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 100;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 101;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 102;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 103;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 104;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 105;
update item set prime = "No", stock = "In stock" WHERE i_id = 106;
update item set prime = "Yes", stock = "Only 20 left in stock - order soon." WHERE i_id = 107;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 108;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 109;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 110;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 111;
update item set prime = "Yes", stock = "Only 11 left in stock - order soon." WHERE i_id = 112;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 113;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 114;
update item set prime = "No", stock = "Only 17 left in stock - order soon." WHERE i_id = 115;
update item set prime = "No", stock = "Only 8 left in stock - order soon." WHERE i_id = 116;
update item set prime = "No", stock = "In stock" WHERE i_id = 117;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 118;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 119;
update item set prime = "No", stock = "In stock" WHERE i_id = 120;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 121;
update item set prime = "Yes", stock = "Only 15 left in stock - order soon." WHERE i_id = 122;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 123;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 124;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 125;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 126;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 127;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 128;
update item set prime = "No", stock = "Only 10 left in stock - order soon." WHERE i_id = 129;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 130;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 131;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 132;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 133;
update item set prime = "No", stock = "In stock" WHERE i_id = 134;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 135;
update item set prime = "No", stock = "Only 20 left in stock - order soon." WHERE i_id = 136;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 137;
update item set prime = "No", stock = "Only 18 left in stock - order soon." WHERE i_id = 138;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 139;
update item set prime = "No", stock = "In stock" WHERE i_id = 140;
update item set prime = "No", stock = "In stock" WHERE i_id = 141;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 142;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 143;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 144;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 145;
update item set prime = "No", stock = "Only 19 left in stock - order soon." WHERE i_id = 146;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 147;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 148;
update item set prime = "No", stock = "Only 10 left in stock - order soon." WHERE i_id = 149;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 150;
update item set prime = "No", stock = "In stock" WHERE i_id = 151;
update item set prime = "No", stock = "Only 8 left in stock - order soon." WHERE i_id = 152;
update item set prime = "No", stock = "Only 3 left in stock - order soon." WHERE i_id = 153;
update item set prime = "No", stock = "Only 14 left in stock - order soon." WHERE i_id = 154;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 155;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 156;
update item set prime = "No", stock = "Only 7 left in stock - order soon." WHERE i_id = 157;
update item set prime = "No", stock = "In stock" WHERE i_id = 158;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 159;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 160;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 161;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 162;
update item set prime = "No", stock = "In stock" WHERE i_id = 163;
update item set prime = "No", stock = "In stock" WHERE i_id = 164;
update item set prime = "Yes", stock = "Only 17 left in stock - order soon." WHERE i_id = 165;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 166;
update item set prime = "Yes", stock = "Only 15 left in stock - order soon." WHERE i_id = 167;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 168;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 169;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 170;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 171;
update item set prime = "No", stock = "In stock" WHERE i_id = 172;
update item set prime = "No", stock = "In stock" WHERE i_id = 173;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 174;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 175;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 176;
update item set prime = "No", stock = "In stock" WHERE i_id = 177;
update item set prime = "No", stock = "In stock" WHERE i_id = 178;
update item set prime = "No", stock = "In stock" WHERE i_id = 179;
update item set prime = "No", stock = "Only 19 left in stock - order soon." WHERE i_id = 180;
update item set prime = "No", stock = "In stock" WHERE i_id = 181;
update item set prime = "No", stock = "In stock" WHERE i_id = 182;
update item set prime = "No", stock = "In stock" WHERE i_id = 183;
update item set prime = "No", stock = "In stock" WHERE i_id = 184;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 185;
update item set prime = "No", stock = "Only 18 left in stock - order soon." WHERE i_id = 186;
update item set prime = "No", stock = "In stock" WHERE i_id = 187;
update item set prime = "No", stock = "In stock" WHERE i_id = 188;
update item set prime = "Yes", stock = "Only 13 left in stock - order soon." WHERE i_id = 189;
update item set prime = "No", stock = "Only 18 left in stock - order soon." WHERE i_id = 190;
update item set prime = "No", stock = "In stock" WHERE i_id = 191;
update item set prime = "No", stock = "In stock" WHERE i_id = 192;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 193;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 194;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 195;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 196;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 197;
update item set prime = "Yes", stock = "Only 15 left in stock - order soon." WHERE i_id = 198;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 199;
update item set prime = "No", stock = "Only 2 left in stock - order soon." WHERE i_id = 200;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 201;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 202;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 203;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 204;
update item set prime = "No", stock = "In stock" WHERE i_id = 205;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 206;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 207;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 208;
update item set prime = "Yes", stock = "Only 9 left in stock - order soon." WHERE i_id = 209;
update item set prime = "Yes", stock = "Only 16 left in stock - order soon." WHERE i_id = 210;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 211;
update item set prime = "No", stock = "In stock" WHERE i_id = 212;
update item set prime = "No", stock = "In stock" WHERE i_id = 213;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 214;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 215;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 216;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 217;
update item set prime = "No", stock = "Only 2 left in stock - order soon." WHERE i_id = 218;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 219;
update item set prime = "No", stock = "In stock" WHERE i_id = 220;
update item set prime = "No", stock = "Only 18 left in stock - order soon." WHERE i_id = 221;
update item set prime = "No", stock = "In stock" WHERE i_id = 222;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 223;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 224;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 225;
update item set prime = "No", stock = "In stock" WHERE i_id = 226;
update item set prime = "No", stock = "In stock" WHERE i_id = 227;
update item set prime = "No", stock = "In stock" WHERE i_id = 228;
update item set prime = "Yes", stock = "Only 9 left in stock - order soon." WHERE i_id = 229;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 230;
update item set prime = "No", stock = "In stock" WHERE i_id = 231;
update item set prime = "Yes", stock = "Only 20 left in stock - order soon." WHERE i_id = 232;
update item set prime = "No", stock = "In stock" WHERE i_id = 233;
update item set prime = "No", stock = "Only 11 left in stock - order soon." WHERE i_id = 234;
update item set prime = "No", stock = "In stock" WHERE i_id = 235;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 236;
update item set prime = "No", stock = "In stock" WHERE i_id = 237;
update item set prime = "No", stock = "In stock" WHERE i_id = 238;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 239;
update item set prime = "No", stock = "In stock" WHERE i_id = 240;
update item set prime = "No", stock = "In stock" WHERE i_id = 241;
update item set prime = "No", stock = "In stock" WHERE i_id = 242;
update item set prime = "No", stock = "In stock" WHERE i_id = 243;
update item set prime = "No", stock = "In stock" WHERE i_id = 244;
update item set prime = "No", stock = "In stock" WHERE i_id = 245;
update item set prime = "No", stock = "In stock" WHERE i_id = 246;
update item set prime = "No", stock = "In stock" WHERE i_id = 247;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 248;
update item set prime = "No", stock = "In stock" WHERE i_id = 249;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 250;
update item set prime = "No", stock = "In stock" WHERE i_id = 251;
update item set prime = "Yes", stock = "Only 11 left in stock - order soon." WHERE i_id = 252;
update item set prime = "No", stock = "Only 20 left in stock - order soon." WHERE i_id = 253;
update item set prime = "No", stock = "In stock" WHERE i_id = 254;
update item set prime = "No", stock = "In stock" WHERE i_id = 255;
update item set prime = "No", stock = "In stock" WHERE i_id = 256;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 257;
update item set prime = "No", stock = "Only 15 left in stock - order soon." WHERE i_id = 258;
update item set prime = "No", stock = "In stock" WHERE i_id = 259;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 260;
update item set prime = "No", stock = "Only 3 left in stock - order soon." WHERE i_id = 261;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 262;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 263;
update item set prime = "No", stock = "In stock" WHERE i_id = 264;
update item set prime = "No", stock = "Only 8 left in stock - order soon." WHERE i_id = 265;
update item set prime = "No", stock = "In stock" WHERE i_id = 266;
update item set prime = "No", stock = "In stock" WHERE i_id = 267;
update item set prime = "No", stock = "In stock" WHERE i_id = 268;
update item set prime = "No", stock = "In stock" WHERE i_id = 269;
update item set prime = "No", stock = "In stock" WHERE i_id = 270;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 271;
update item set prime = "No", stock = "In stock" WHERE i_id = 272;
update item set prime = "No", stock = "In stock" WHERE i_id = 273;
update item set prime = "No", stock = "In stock" WHERE i_id = 274;
update item set prime = "No", stock = "In stock" WHERE i_id = 275;
update item set prime = "No", stock = "In stock" WHERE i_id = 276;
update item set prime = "No", stock = "In stock" WHERE i_id = 277;
update item set prime = "No", stock = "In stock" WHERE i_id = 278;
update item set prime = "No", stock = "In stock" WHERE i_id = 279;
update item set prime = "No", stock = "In stock" WHERE i_id = 280;
update item set prime = "No", stock = "In stock" WHERE i_id = 281;
update item set prime = "No", stock = "In stock" WHERE i_id = 282;
update item set prime = "No", stock = "In stock" WHERE i_id = 283;
update item set prime = "No", stock = "In stock" WHERE i_id = 284;
update item set prime = "No", stock = "Only 3 left in stock - order soon." WHERE i_id = 285;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 286;
update item set prime = "No", stock = "In stock" WHERE i_id = 287;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 288;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 289;
update item set prime = "No", stock = "In stock" WHERE i_id = 290;
update item set prime = "No", stock = "In stock" WHERE i_id = 291;
update item set prime = "No", stock = "In stock" WHERE i_id = 292;
update item set prime = "No", stock = "In stock" WHERE i_id = 293;
update item set prime = "No", stock = "In stock" WHERE i_id = 294;
update item set prime = "No", stock = "In stock" WHERE i_id = 295;
update item set prime = "No", stock = "In stock" WHERE i_id = 296;
update item set prime = "No", stock = "In stock" WHERE i_id = 297;
update item set prime = "No", stock = "In stock" WHERE i_id = 298;
update item set prime = "No", stock = "In stock" WHERE i_id = 299;
update item set prime = "No", stock = "In stock" WHERE i_id = 300;
update item set prime = "No", stock = "In stock" WHERE i_id = 301;
update item set prime = "No", stock = "Only 3 left in stock - order soon." WHERE i_id = 302;
update item set prime = "No", stock = "In stock" WHERE i_id = 303;
update item set prime = "Yes", stock = "Only 9 left in stock - order soon." WHERE i_id = 304;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 305;
update item set prime = "No", stock = "In stock" WHERE i_id = 306;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 307;
update item set prime = "No", stock = "In stock" WHERE i_id = 308;
update item set prime = "No", stock = "In stock" WHERE i_id = 309;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 310;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 311;
update item set prime = "No", stock = "In stock" WHERE i_id = 312;
update item set prime = "No", stock = "In stock" WHERE i_id = 313;
update item set prime = "No", stock = "In stock" WHERE i_id = 314;
update item set prime = "No", stock = "In stock" WHERE i_id = 315;
update item set prime = "No", stock = "In stock" WHERE i_id = 316;
update item set prime = "No", stock = "In stock" WHERE i_id = 317;
update item set prime = "No", stock = "In stock" WHERE i_id = 318;
update item set prime = "No", stock = "In stock" WHERE i_id = 319;
update item set prime = "No", stock = "Only 2 left in stock - order soon." WHERE i_id = 320;
update item set prime = "No", stock = "In stock" WHERE i_id = 321;
update item set prime = "No", stock = "In stock" WHERE i_id = 322;
update item set prime = "No", stock = "In stock" WHERE i_id = 323;
update item set prime = "No", stock = "In stock" WHERE i_id = 324;
update item set prime = "No", stock = "In stock" WHERE i_id = 325;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 326;
update item set prime = "No", stock = "In stock" WHERE i_id = 327;
update item set prime = "No", stock = "In stock" WHERE i_id = 328;
update item set prime = "No", stock = "In stock" WHERE i_id = 329;
update item set prime = "No", stock = "In stock" WHERE i_id = 330;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 331;
update item set prime = "No", stock = "In stock" WHERE i_id = 332;
update item set prime = "No", stock = "In stock" WHERE i_id = 333;
update item set prime = "No", stock = "In stock" WHERE i_id = 334;
update item set prime = "No", stock = "Only 7 left in stock - order soon." WHERE i_id = 335;
update item set prime = "No", stock = "In stock" WHERE i_id = 336;
update item set prime = "No", stock = "In stock" WHERE i_id = 337;
update item set prime = "No", stock = "In stock" WHERE i_id = 338;
update item set prime = "No", stock = "In stock" WHERE i_id = 339;
update item set prime = "No", stock = "In stock" WHERE i_id = 340;
update item set prime = "No", stock = "In stock" WHERE i_id = 341;
update item set prime = "No", stock = "In stock" WHERE i_id = 342;
update item set prime = "No", stock = "In stock" WHERE i_id = 343;
update item set prime = "No", stock = "In stock" WHERE i_id = 344;
update item set prime = "No", stock = "In stock" WHERE i_id = 345;
update item set prime = "No", stock = "In stock" WHERE i_id = 346;
update item set prime = "No", stock = "In stock" WHERE i_id = 347;
update item set prime = "No", stock = "In stock" WHERE i_id = 348;
update item set prime = "No", stock = "In stock" WHERE i_id = 349;
update item set prime = "No", stock = "In stock" WHERE i_id = 350;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 351;
update item set prime = "No", stock = "In stock" WHERE i_id = 352;
update item set prime = "No", stock = "In stock" WHERE i_id = 353;
update item set prime = "No", stock = "In stock" WHERE i_id = 354;
update item set prime = "No", stock = "In stock" WHERE i_id = 355;
update item set prime = "No", stock = "In stock" WHERE i_id = 356;
update item set prime = "No", stock = "In stock" WHERE i_id = 357;
update item set prime = "No", stock = "In stock" WHERE i_id = 358;
update item set prime = "No", stock = "In stock" WHERE i_id = 359;
update item set prime = "No", stock = "In stock" WHERE i_id = 360;
update item set prime = "No", stock = "In stock" WHERE i_id = 361;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 363;
update item set prime = "No", stock = "In stock" WHERE i_id = 364;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 365;
update item set prime = "No", stock = "In stock" WHERE i_id = 366;
update item set prime = "No", stock = "In stock" WHERE i_id = 367;
update item set prime = "No", stock = "In stock" WHERE i_id = 368;
update item set prime = "No", stock = "In stock" WHERE i_id = 369;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 370;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 371;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 372;
update item set prime = "No", stock = "In stock" WHERE i_id = 373;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 374;
update item set prime = "No", stock = "In stock" WHERE i_id = 375;
update item set prime = "No", stock = "In stock" WHERE i_id = 376;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 377;
update item set prime = "No", stock = "In stock" WHERE i_id = 378;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 379;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 380;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 381;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 382;
update item set prime = "No", stock = "Only 19 left in stock - order soon." WHERE i_id = 383;
update item set prime = "No", stock = "In stock" WHERE i_id = 384;
update item set prime = "No", stock = "In stock" WHERE i_id = 385;
update item set prime = "No", stock = "In stock" WHERE i_id = 386;
update item set prime = "No", stock = "In stock" WHERE i_id = 387;
update item set prime = "No", stock = "Only 20 left in stock - order soon." WHERE i_id = 388;
update item set prime = "No", stock = "In stock" WHERE i_id = 389;
update item set prime = "No", stock = "In stock" WHERE i_id = 390;
update item set prime = "No", stock = "In stock" WHERE i_id = 391;
update item set prime = "No", stock = "In stock" WHERE i_id = 392;
update item set prime = "No", stock = "In stock" WHERE i_id = 393;
update item set prime = "No", stock = "In stock" WHERE i_id = 394;
update item set prime = "No", stock = "Only 9 left in stock - order soon." WHERE i_id = 395;
update item set prime = "No", stock = "In stock" WHERE i_id = 396;
update item set prime = "No", stock = "In stock" WHERE i_id = 397;
update item set prime = "No", stock = "In stock" WHERE i_id = 398;
update item set prime = "No", stock = "In stock" WHERE i_id = 399;
update item set prime = "No", stock = "In stock" WHERE i_id = 400;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 401;
update item set prime = "No", stock = "In stock" WHERE i_id = 402;
update item set prime = "No", stock = "In stock" WHERE i_id = 403;
update item set prime = "No", stock = "In stock" WHERE i_id = 404;
update item set prime = "No", stock = "In stock" WHERE i_id = 405;
update item set prime = "No", stock = "In stock" WHERE i_id = 406;
update item set prime = "No", stock = "In stock" WHERE i_id = 407;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 408;
update item set prime = "No", stock = "In stock" WHERE i_id = 409;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 410;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 411;
update item set prime = "No", stock = "In stock" WHERE i_id = 412;
update item set prime = "No", stock = "In stock" WHERE i_id = 413;
update item set prime = "No", stock = "In stock" WHERE i_id = 414;
update item set prime = "No", stock = "In stock" WHERE i_id = 415;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 416;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 417;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 418;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 419;
update item set prime = "No", stock = "In stock" WHERE i_id = 420;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 421;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 422;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 423;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 424;
update item set prime = "No", stock = "In stock" WHERE i_id = 425;
update item set prime = "No", stock = "In stock" WHERE i_id = 426;
update item set prime = "No", stock = "In stock" WHERE i_id = 427;
update item set prime = "No", stock = "Only 2 left in stock - order soon." WHERE i_id = 428;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 429;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 430;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 431;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 432;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 433;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 434;
update item set prime = "Yes", stock = "Only 11 left in stock - order soon." WHERE i_id = 435;
update item set prime = "No", stock = "In stock" WHERE i_id = 436;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 437;
update item set prime = "No", stock = "Only 3 left in stock - order soon." WHERE i_id = 438;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 439;
update item set prime = "No", stock = "In stock" WHERE i_id = 440;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 441;
update item set prime = "No", stock = "In stock" WHERE i_id = 442;
update item set prime = "No", stock = "In stock" WHERE i_id = 443;
update item set prime = "No", stock = "In stock" WHERE i_id = 444;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 445;
update item set prime = "No", stock = "In stock" WHERE i_id = 446;
update item set prime = "No", stock = "In stock" WHERE i_id = 447;
update item set prime = "No", stock = "In stock" WHERE i_id = 448;
update item set prime = "Yes", stock = "Only 16 left in stock - order soon." WHERE i_id = 449;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 450;
update item set prime = "Yes", stock = "Only 17 left in stock - order soon." WHERE i_id = 451;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 452;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 453;
update item set prime = "No", stock = "Only 5 left in stock - order soon." WHERE i_id = 454;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 455;
update item set prime = "No", stock = "In stock" WHERE i_id = 456;
update item set prime = "No", stock = "Only 3 left in stock - order soon." WHERE i_id = 457;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 458;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 459;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 460;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 461;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 462;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 463;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 464;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 465;
update item set prime = "Yes", stock = "Only 17 left in stock - order soon." WHERE i_id = 466;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 467;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 468;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 469;
update item set prime = "No", stock = "Only 5 left in stock - order soon." WHERE i_id = 470;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 471;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 472;
update item set prime = "No", stock = "In stock" WHERE i_id = 473;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 474;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 475;
update item set prime = "No", stock = "Only 20 left in stock - order soon." WHERE i_id = 476;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 477;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 478;
update item set prime = "No", stock = "In stock" WHERE i_id = 479;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 480;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 481;
update item set prime = "No", stock = "In stock" WHERE i_id = 482;
update item set prime = "Yes", stock = "Only 9 left in stock - order soon." WHERE i_id = 483;
update item set prime = "No", stock = "In stock" WHERE i_id = 484;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 485;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 486;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 487;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 488;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 489;
update item set prime = "No", stock = "Only 11 left in stock - order soon." WHERE i_id = 490;
update item set prime = "No", stock = "Only 11 left in stock - order soon." WHERE i_id = 491;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 492;
update item set prime = "No", stock = "In stock" WHERE i_id = 493;
update item set prime = "Yes", stock = "Only 15 left in stock - order soon." WHERE i_id = 494;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 495;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 496;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 497;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 498;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 499;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 500;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 501;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 502;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 503;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 504;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 505;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 506;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 507;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 508;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 509;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 510;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 511;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 512;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 513;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 514;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 515;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 516;
update item set prime = "No", stock = "In stock" WHERE i_id = 517;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 518;
update item set prime = "No", stock = "In stock" WHERE i_id = 519;
update item set prime = "No", stock = "In stock" WHERE i_id = 520;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 521;
update item set prime = "No", stock = "Only 20 left in stock - order soon." WHERE i_id = 522;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 523;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 524;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 525;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 526;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 527;
update item set prime = "No", stock = "In stock" WHERE i_id = 528;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 529;
update item set prime = "No", stock = "In stock" WHERE i_id = 530;
update item set prime = "No", stock = "In stock" WHERE i_id = 531;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 532;
update item set prime = "No", stock = "In stock" WHERE i_id = 533;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 534;
update item set prime = "No", stock = "In stock" WHERE i_id = 535;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 536;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 537;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 538;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 539;
update item set prime = "Yes", stock = "Only 17 left in stock - order soon." WHERE i_id = 540;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 541;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 542;
update item set prime = "Yes", stock = "Only 11 left in stock - order soon." WHERE i_id = 543;
update item set prime = "Yes", stock = "Only 17 left in stock - order soon." WHERE i_id = 544;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 545;
update item set prime = "Yes", stock = "Only 12 left in stock - order soon." WHERE i_id = 546;
update item set prime = "No", stock = "In stock" WHERE i_id = 547;
update item set prime = "No", stock = "Only 6 left in stock - order soon." WHERE i_id = 548;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 549;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 550;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 551;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 552;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 553;
update item set prime = "No", stock = "Only 6 left in stock - order soon." WHERE i_id = 554;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 555;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 556;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 557;
update item set prime = "No", stock = "In stock" WHERE i_id = 558;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 559;
update item set prime = "Yes", stock = "Only 16 left in stock - order soon." WHERE i_id = 560;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 561;
update item set prime = "No", stock = "In stock" WHERE i_id = 562;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 563;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 564;
update item set prime = "No", stock = "Only 2 left in stock - order soon." WHERE i_id = 565;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 566;
update item set prime = "Yes", stock = "Only 9 left in stock - order soon." WHERE i_id = 567;
update item set prime = "No", stock = "In stock" WHERE i_id = 568;
update item set prime = "No", stock = "Only 12 left in stock - order soon." WHERE i_id = 569;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 570;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 571;
update item set prime = "Yes", stock = "Only 20 left in stock - order soon." WHERE i_id = 572;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 573;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 574;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 575;
update item set prime = "No", stock = "In stock" WHERE i_id = 576;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 577;
update item set prime = "No", stock = "In stock" WHERE i_id = 578;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 579;
update item set prime = "Yes", stock = "Only 17 left in stock - order soon." WHERE i_id = 580;
update item set prime = "Yes", stock = "Only 16 left in stock - order soon." WHERE i_id = 581;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 582;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 583;
update item set prime = "No", stock = "In stock" WHERE i_id = 584;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 585;
update item set prime = "No", stock = "In stock" WHERE i_id = 586;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 587;
update item set prime = "No", stock = "In stock" WHERE i_id = 588;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 589;
update item set prime = "No", stock = "In stock" WHERE i_id = 590;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 591;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 592;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 593;
update item set prime = "No", stock = "In stock" WHERE i_id = 594;
update item set prime = "Yes", stock = "Only 20 left in stock - order soon." WHERE i_id = 595;
update item set prime = "No", stock = "In stock" WHERE i_id = 596;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 597;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 598;
update item set prime = "No", stock = "Only 2 left in stock - order soon." WHERE i_id = 599;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 600;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 601;
update item set prime = "Yes", stock = "Only 20 left in stock - order soon." WHERE i_id = 602;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 603;
update item set prime = "No", stock = "In stock" WHERE i_id = 604;
update item set prime = "No", stock = "In stock" WHERE i_id = 605;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 606;
update item set prime = "No", stock = "In stock" WHERE i_id = 607;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 608;
update item set prime = "No", stock = "In stock" WHERE i_id = 609;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 610;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 611;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 612;
update item set prime = "No", stock = "In stock" WHERE i_id = 613;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 614;
update item set prime = "Yes", stock = "Only 19 left in stock - order soon." WHERE i_id = 615;
update item set prime = "Yes", stock = "Only 17 left in stock - order soon." WHERE i_id = 616;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 617;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 618;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 619;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 620;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 621;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 622;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 623;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 624;
update item set prime = "Yes", stock = "Only 16 left in stock - order soon." WHERE i_id = 625;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 626;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 627;
update item set prime = "No", stock = "Only 20 left in stock - order soon." WHERE i_id = 628;
update item set prime = "No", stock = "Only 7 left in stock - order soon." WHERE i_id = 629;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 630;
update item set prime = "No", stock = "In stock" WHERE i_id = 631;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 632;
update item set prime = "No", stock = "Only 2 left in stock - order soon." WHERE i_id = 633;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 634;
update item set prime = "No", stock = "In stock" WHERE i_id = 635;
update item set prime = "Yes", stock = "Only 20 left in stock - order soon." WHERE i_id = 636;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 637;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 638;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 639;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 640;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 641;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 642;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 643;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 644;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 645;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 646;
update item set prime = "Yes", stock = "Only 15 left in stock - order soon." WHERE i_id = 647;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 648;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 649;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 650;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 651;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 652;
update item set prime = "Yes", stock = "Only 17 left in stock - order soon." WHERE i_id = 653;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 654;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 655;
update item set prime = "Yes", stock = "Only 12 left in stock - order soon." WHERE i_id = 656;
update item set prime = "No", stock = "Only 2 left in stock - order soon." WHERE i_id = 657;
update item set prime = "Yes", stock = "Only 16 left in stock - order soon." WHERE i_id = 658;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 659;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 660;
update item set prime = "No", stock = "In stock" WHERE i_id = 661;
update item set prime = "Yes", stock = "Only 16 left in stock - order soon." WHERE i_id = 662;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 663;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 664;
update item set prime = "No", stock = "Only 7 left in stock - order soon." WHERE i_id = 665;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 666;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 667;
update item set prime = "Yes", stock = "Only 12 left in stock - order soon." WHERE i_id = 668;
update item set prime = "No", stock = "Only 6 left in stock - order soon." WHERE i_id = 669;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 670;
update item set prime = "Yes", stock = "Only 13 left in stock - order soon." WHERE i_id = 671;
update item set prime = "No", stock = "Only 12 left in stock - order soon." WHERE i_id = 672;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 673;
update item set prime = "No", stock = "In stock" WHERE i_id = 674;
update item set prime = "No", stock = "In stock" WHERE i_id = 675;
update item set prime = "No", stock = "In stock" WHERE i_id = 676;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 677;
update item set prime = "No", stock = "Only 12 left in stock - order soon." WHERE i_id = 678;
update item set prime = "No", stock = "Only 13 left in stock - order soon." WHERE i_id = 679;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 680;
update item set prime = "No", stock = "In stock" WHERE i_id = 681;
update item set prime = "Yes", stock = "Only 16 left in stock - order soon." WHERE i_id = 682;
update item set prime = "Yes", stock = "Only 20 left in stock - order soon." WHERE i_id = 683;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 684;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 685;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 686;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 687;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 688;
update item set prime = "No", stock = "In stock" WHERE i_id = 689;
update item set prime = "No", stock = "In stock" WHERE i_id = 690;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 691;
update item set prime = "No", stock = "Only 16 left in stock - order soon." WHERE i_id = 692;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 693;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 694;
update item set prime = "No", stock = "In stock" WHERE i_id = 695;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 696;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 697;
update item set prime = "No", stock = "In stock" WHERE i_id = 698;
update item set prime = "No", stock = "In stock" WHERE i_id = 699;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 700;
update item set prime = "No", stock = "In stock" WHERE i_id = 701;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 702;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 703;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 704;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 705;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 706;
update item set prime = "No", stock = "In stock" WHERE i_id = 707;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 708;
update item set prime = "No", stock = "In stock" WHERE i_id = 709;
update item set prime = "No", stock = "In stock" WHERE i_id = 710;
update item set prime = "No", stock = "In stock" WHERE i_id = 711;
update item set prime = "No", stock = "Only 11 left in stock - order soon." WHERE i_id = 712;
update item set prime = "No", stock = "In stock" WHERE i_id = 713;
update item set prime = "No", stock = "In stock" WHERE i_id = 714;
update item set prime = "No", stock = "In stock" WHERE i_id = 715;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 716;
update item set prime = "Yes", stock = "Only 15 left in stock - order soon." WHERE i_id = 717;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 718;
update item set prime = "No", stock = "In stock" WHERE i_id = 719;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 720;
update item set prime = "No", stock = "Only 3 left in stock - order soon." WHERE i_id = 721;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 722;
update item set prime = "No", stock = "In stock" WHERE i_id = 723;
update item set prime = "No", stock = "In stock" WHERE i_id = 724;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 725;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 726;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 727;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 728;
update item set prime = "Yes", stock = "Only 19 left in stock - order soon." WHERE i_id = 729;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 730;
update item set prime = "No", stock = "In stock" WHERE i_id = 731;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 732;
update item set prime = "No", stock = "Only 3 left in stock - order soon." WHERE i_id = 733;
update item set prime = "Yes", stock = "Only 11 left in stock - order soon." WHERE i_id = 734;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 735;
update item set prime = "No", stock = "In stock" WHERE i_id = 736;
update item set prime = "Yes", stock = "Only 15 left in stock - order soon." WHERE i_id = 737;
update item set prime = "No", stock = "In stock" WHERE i_id = 738;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 739;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 740;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 741;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 742;
update item set prime = "Yes", stock = "Only 4 left in stock - order soon." WHERE i_id = 743;
update item set prime = "No", stock = "In stock" WHERE i_id = 744;
update item set prime = "No", stock = "In stock" WHERE i_id = 745;
update item set prime = "No", stock = "In stock" WHERE i_id = 746;
update item set prime = "No", stock = "In stock" WHERE i_id = 747;
update item set prime = "No", stock = "In stock" WHERE i_id = 748;
update item set prime = "No", stock = "In stock" WHERE i_id = 749;
update item set prime = "No", stock = "In stock" WHERE i_id = 750;
update item set prime = "Yes", stock = "Only 17 left in stock - order soon." WHERE i_id = 751;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 752;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 753;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 754;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 755;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 756;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 757;
update item set prime = "Yes", stock = "Only 8 left in stock - order soon." WHERE i_id = 758;
update item set prime = "No", stock = "In stock" WHERE i_id = 759;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 760;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 761;
update item set prime = "No", stock = "In stock" WHERE i_id = 762;
update item set prime = "Yes", stock = "Only 13 left in stock - order soon." WHERE i_id = 763;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 764;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 765;
update item set prime = "No", stock = "Only 11 left in stock - order soon." WHERE i_id = 766;
update item set prime = "Yes", stock = "Only 13 left in stock - order soon." WHERE i_id = 767;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 768;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 769;
update item set prime = "No", stock = "In stock" WHERE i_id = 770;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 771;
update item set prime = "No", stock = "In stock" WHERE i_id = 772;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 773;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 774;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 775;
update item set prime = "No", stock = "Only 10 left in stock - order soon." WHERE i_id = 776;
update item set prime = "No", stock = "In stock" WHERE i_id = 777;
update item set prime = "No", stock = "In stock" WHERE i_id = 778;
update item set prime = "No", stock = "Only 13 left in stock - order soon." WHERE i_id = 779;
update item set prime = "No", stock = "In stock" WHERE i_id = 780;
update item set prime = "No", stock = "In stock" WHERE i_id = 781;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 782;
update item set prime = "No", stock = "In stock" WHERE i_id = 783;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 784;
update item set prime = "No", stock = "Only 7 left in stock - order soon." WHERE i_id = 785;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 786;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 787;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 788;
update item set prime = "No", stock = "In stock" WHERE i_id = 789;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 790;
update item set prime = "No", stock = "Only 12 left in stock - order soon." WHERE i_id = 791;
update item set prime = "No", stock = "In stock" WHERE i_id = 792;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 793;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 794;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 795;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 796;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 797;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 798;
update item set prime = "No", stock = "Only 10 left in stock - order soon." WHERE i_id = 799;
update item set prime = "Yes", stock = "Only 12 left in stock - order soon." WHERE i_id = 800;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 801;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 802;
update item set prime = "No", stock = "In stock" WHERE i_id = 803;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 804;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 805;
update item set prime = "No", stock = "In stock" WHERE i_id = 806;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 807;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 808;
update item set prime = "No", stock = "In stock" WHERE i_id = 809;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 810;
update item set prime = "No", stock = "In stock" WHERE i_id = 811;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 812;
update item set prime = "No", stock = "In stock" WHERE i_id = 813;
update item set prime = "No", stock = "In stock" WHERE i_id = 814;
update item set prime = "No", stock = "In stock" WHERE i_id = 815;
update item set prime = "No", stock = "Only 19 left in stock - order soon." WHERE i_id = 816;
update item set prime = "No", stock = "In stock" WHERE i_id = 817;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 818;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 819;
update item set prime = "No", stock = "In stock" WHERE i_id = 820;
update item set prime = "No", stock = "Only 13 left in stock - order soon." WHERE i_id = 821;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 822;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 823;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 824;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 825;
update item set prime = "Yes", stock = "Only 9 left in stock - order soon." WHERE i_id = 826;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 827;
update item set prime = "Yes", stock = "Only 20 left in stock - order soon." WHERE i_id = 828;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 829;
update item set prime = "No", stock = "Only 10 left in stock - order soon." WHERE i_id = 830;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 831;
update item set prime = "Yes", stock = "Only 18 left in stock - order soon." WHERE i_id = 832;
update item set prime = "Yes", stock = "Only 2 left in stock - order soon." WHERE i_id = 833;
update item set prime = "No", stock = "In stock" WHERE i_id = 834;
update item set prime = "Yes", stock = "Only 14 left in stock - order soon." WHERE i_id = 835;
update item set prime = "No", stock = "In stock" WHERE i_id = 836;
update item set prime = "No", stock = "Only 14 left in stock - order soon." WHERE i_id = 837;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 838;
update item set prime = "No", stock = "In stock" WHERE i_id = 839;
update item set prime = "No", stock = "Only 12 left in stock - order soon." WHERE i_id = 840;
update item set prime = "No", stock = "In stock" WHERE i_id = 841;
update item set prime = "No", stock = "In stock" WHERE i_id = 842;
update item set prime = "No", stock = "Only 17 left in stock - order soon." WHERE i_id = 843;
update item set prime = "No", stock = "In stock" WHERE i_id = 844;
update item set prime = "No", stock = "In stock" WHERE i_id = 845;
update item set prime = "No", stock = "In stock" WHERE i_id = 846;
update item set prime = "No", stock = "In stock" WHERE i_id = 847;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 848;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 849;
update item set prime = "No", stock = "In stock" WHERE i_id = 850;
update item set prime = "No", stock = "Only 9 left in stock - order soon." WHERE i_id = 851;
update item set prime = "No", stock = "In stock" WHERE i_id = 852;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 853;
update item set prime = "No", stock = "Only 20 left in stock - order soon." WHERE i_id = 854;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 855;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 856;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 857;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 858;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 859;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 860;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 861;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 862;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 863;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 864;
update item set prime = "Yes", stock = "Only 16 left in stock - order soon." WHERE i_id = 865;
update item set prime = "No", stock = "Only 4 left in stock - order soon." WHERE i_id = 866;
update item set prime = "No", stock = "Only 16 left in stock - order soon." WHERE i_id = 867;
update item set prime = "No", stock = "In stock" WHERE i_id = 868;
update item set prime = "Yes", stock = "Only 19 left in stock - order soon." WHERE i_id = 869;
update item set prime = "Yes", stock = "Only 13 left in stock - order soon." WHERE i_id = 870;
update item set prime = "Yes", stock = "Only 13 left in stock - order soon." WHERE i_id = 871;
update item set prime = "Yes", stock = "Only 5 left in stock - order soon." WHERE i_id = 872;
update item set prime = "No", stock = "In stock" WHERE i_id = 873;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 874;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 875;
update item set prime = "Yes", stock = "Only 11 left in stock - order soon." WHERE i_id = 876;
update item set prime = "No", stock = "In stock" WHERE i_id = 877;
update item set prime = "Yes", stock = "Only 10 left in stock - order soon." WHERE i_id = 878;
update item set prime = "Yes", stock = "Only 7 left in stock - order soon." WHERE i_id = 879;
update item set prime = "No", stock = "In stock" WHERE i_id = 880;
update item set prime = "No", stock = "In stock" WHERE i_id = 881;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 882;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 883;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 884;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 885;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 886;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 887;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 888;
update item set prime = "No", stock = "In stock" WHERE i_id = 889;
update item set prime = "No", stock = "Only 11 left in stock - order soon." WHERE i_id = 890;
update item set prime = "No", stock = "Only 18 left in stock - order soon." WHERE i_id = 891;
update item set prime = "Yes", stock = "Only 6 left in stock - order soon." WHERE i_id = 892;
update item set prime = "No", stock = "In stock" WHERE i_id = 893;
update item set prime = "No", stock = "In stock" WHERE i_id = 894;
update item set prime = "No", stock = "In stock" WHERE i_id = 895;
update item set prime = "No", stock = "Only 1 left in stock - order soon." WHERE i_id = 896;
update item set prime = "No", stock = "In stock" WHERE i_id = 897;
update item set prime = "Yes", stock = "Only 9 left in stock - order soon." WHERE i_id = 898;
update item set prime = "No", stock = "In stock" WHERE i_id = 899;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 900;
update item set prime = "No", stock = "In stock" WHERE i_id = 901;
update item set prime = "No", stock = "In stock" WHERE i_id = 902;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 903;
update item set prime = "No", stock = "Only 7 left in stock - order soon." WHERE i_id = 904;
update item set prime = "Yes", stock = "Only 1 left in stock - order soon." WHERE i_id = 905;
update item set prime = "Yes", stock = "Only 3 left in stock - order soon." WHERE i_id = 906;
update item set prime = "No", stock = "In stock" WHERE i_id = 907;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 908;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 909;
update item set prime = "No", stock = "In stock" WHERE i_id = 910;
update item set prime = "No", stock = "In stock" WHERE i_id = 911;
update item set prime = "No", stock = "Only 2 left in stock - order soon." WHERE i_id = 912;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 913;
update item set prime = "No", stock = "In stock" WHERE i_id = 914;
update item set prime = "Yes", stock = "In stock" WHERE i_id = 915;
update item set prime = "No", stock = "In stock" WHERE i_id = 916;
update item set prime = "No", stock = "Only 2 left in stock - order soon." WHERE i_id = 917;
