update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 1;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 2;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 3;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 4;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 5;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 6;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 7;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 8;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 9;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 10;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 11;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 12;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 13;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 14;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 15;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 16;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 17;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 18;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 19;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 20;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 21;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 22;
update author set a_fname = "Yes", a_lname = "Only 9 left in stock - order soon." WHERE a_id = 23;
update author set a_fname = "Yes", a_lname = "Only 9 left in stock - order soon." WHERE a_id = 24;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 25;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 26;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 27;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 28;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 29;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 30;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 31;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 32;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 33;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 34;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 35;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 36;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 37;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 38;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 39;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 40;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 41;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 42;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 43;
update author set a_fname = "No", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 44;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 45;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 46;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 47;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 48;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 49;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 50;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 51;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 52;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 53;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 54;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 55;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 56;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 57;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 58;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 59;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 60;
update author set a_fname = "No", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 61;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 62;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 63;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 64;
update author set a_fname = "Yes", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 65;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 66;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 67;
update author set a_fname = "No", a_lname = "Only 15 left in stock - order soon." WHERE a_id = 68;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 69;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 70;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 71;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 72;
update author set a_fname = "Yes", a_lname = "Only 15 left in stock - order soon." WHERE a_id = 73;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 74;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 75;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 76;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 77;
update author set a_fname = "No", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 78;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 79;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 80;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 81;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 82;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 83;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 84;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 85;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 86;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 87;
update author set a_fname = "No", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 88;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 89;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 90;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 91;
update author set a_fname = "Yes", a_lname = "Only 19 left in stock - order soon." WHERE a_id = 92;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 93;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 94;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 95;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 96;
update author set a_fname = "Yes", a_lname = "Only 19 left in stock - order soon." WHERE a_id = 97;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 98;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 99;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 100;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 101;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 102;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 103;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 104;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 105;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 106;
update author set a_fname = "Yes", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 107;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 108;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 109;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 110;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 111;
update author set a_fname = "Yes", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 112;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 113;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 114;
update author set a_fname = "No", a_lname = "Only 17 left in stock - order soon." WHERE a_id = 115;
update author set a_fname = "No", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 116;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 117;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 118;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 119;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 120;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 121;
update author set a_fname = "Yes", a_lname = "Only 15 left in stock - order soon." WHERE a_id = 122;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 123;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 124;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 125;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 126;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 127;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 128;
update author set a_fname = "No", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 129;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 130;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 131;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 132;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 133;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 134;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 135;
update author set a_fname = "No", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 136;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 137;
update author set a_fname = "No", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 138;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 139;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 140;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 141;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 142;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 143;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 144;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 145;
update author set a_fname = "No", a_lname = "Only 19 left in stock - order soon." WHERE a_id = 146;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 147;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 148;
update author set a_fname = "No", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 149;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 150;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 151;
update author set a_fname = "No", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 152;
update author set a_fname = "No", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 153;
update author set a_fname = "No", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 154;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 155;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 156;
update author set a_fname = "No", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 157;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 158;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 159;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 160;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 161;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 162;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 163;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 164;
update author set a_fname = "Yes", a_lname = "Only 17 left in stock - order soon." WHERE a_id = 165;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 166;
update author set a_fname = "Yes", a_lname = "Only 15 left in stock - order soon." WHERE a_id = 167;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 168;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 169;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 170;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 171;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 172;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 173;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 174;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 175;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 176;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 177;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 178;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 179;
update author set a_fname = "No", a_lname = "Only 19 left in stock - order soon." WHERE a_id = 180;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 181;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 182;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 183;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 184;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 185;
update author set a_fname = "No", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 186;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 187;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 188;
update author set a_fname = "Yes", a_lname = "Only 13 left in stock - order soon." WHERE a_id = 189;
update author set a_fname = "No", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 190;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 191;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 192;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 193;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 194;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 195;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 196;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 197;
update author set a_fname = "Yes", a_lname = "Only 15 left in stock - order soon." WHERE a_id = 198;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 199;
update author set a_fname = "No", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 200;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 201;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 202;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 203;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 204;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 205;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 206;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 207;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 208;
update author set a_fname = "Yes", a_lname = "Only 9 left in stock - order soon." WHERE a_id = 209;
update author set a_fname = "Yes", a_lname = "Only 16 left in stock - order soon." WHERE a_id = 210;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 211;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 212;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 213;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 214;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 215;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 216;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 217;
update author set a_fname = "No", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 218;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 219;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 220;
update author set a_fname = "No", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 221;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 222;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 223;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 224;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 225;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 226;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 227;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 228;
update author set a_fname = "Yes", a_lname = "Only 9 left in stock - order soon." WHERE a_id = 229;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 230;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 231;
update author set a_fname = "Yes", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 232;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 233;
update author set a_fname = "No", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 234;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 235;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 236;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 237;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 238;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 239;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 240;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 241;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 242;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 243;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 244;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 245;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 246;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 247;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 248;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 249;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 250;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 251;
update author set a_fname = "Yes", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 252;
update author set a_fname = "No", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 253;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 254;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 255;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 256;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 257;
update author set a_fname = "No", a_lname = "Only 15 left in stock - order soon." WHERE a_id = 258;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 259;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 260;
update author set a_fname = "No", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 261;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 262;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 263;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 264;
update author set a_fname = "No", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 265;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 266;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 267;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 268;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 269;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 270;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 271;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 272;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 273;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 274;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 275;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 276;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 277;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 278;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 279;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 280;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 281;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 282;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 283;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 284;
update author set a_fname = "No", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 285;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 286;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 287;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 288;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 289;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 290;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 291;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 292;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 293;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 294;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 295;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 296;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 297;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 298;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 299;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 300;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 301;
update author set a_fname = "No", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 302;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 303;
update author set a_fname = "Yes", a_lname = "Only 9 left in stock - order soon." WHERE a_id = 304;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 305;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 306;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 307;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 308;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 309;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 310;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 311;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 312;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 313;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 314;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 315;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 316;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 317;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 318;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 319;
update author set a_fname = "No", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 320;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 321;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 322;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 323;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 324;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 325;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 326;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 327;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 328;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 329;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 330;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 331;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 332;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 333;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 334;
update author set a_fname = "No", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 335;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 336;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 337;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 338;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 339;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 340;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 341;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 342;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 343;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 344;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 345;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 346;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 347;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 348;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 349;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 350;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 351;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 352;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 353;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 354;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 355;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 356;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 357;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 358;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 359;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 360;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 361;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 363;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 364;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 365;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 366;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 367;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 368;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 369;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 370;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 371;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 372;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 373;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 374;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 375;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 376;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 377;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 378;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 379;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 380;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 381;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 382;
update author set a_fname = "No", a_lname = "Only 19 left in stock - order soon." WHERE a_id = 383;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 384;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 385;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 386;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 387;
update author set a_fname = "No", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 388;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 389;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 390;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 391;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 392;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 393;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 394;
update author set a_fname = "No", a_lname = "Only 9 left in stock - order soon." WHERE a_id = 395;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 396;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 397;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 398;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 399;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 400;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 401;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 402;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 403;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 404;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 405;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 406;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 407;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 408;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 409;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 410;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 411;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 412;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 413;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 414;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 415;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 416;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 417;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 418;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 419;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 420;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 421;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 422;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 423;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 424;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 425;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 426;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 427;
update author set a_fname = "No", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 428;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 429;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 430;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 431;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 432;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 433;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 434;
update author set a_fname = "Yes", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 435;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 436;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 437;
update author set a_fname = "No", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 438;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 439;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 440;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 441;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 442;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 443;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 444;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 445;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 446;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 447;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 448;
update author set a_fname = "Yes", a_lname = "Only 16 left in stock - order soon." WHERE a_id = 449;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 450;
update author set a_fname = "Yes", a_lname = "Only 17 left in stock - order soon." WHERE a_id = 451;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 452;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 453;
update author set a_fname = "No", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 454;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 455;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 456;
update author set a_fname = "No", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 457;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 458;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 459;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 460;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 461;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 462;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 463;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 464;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 465;
update author set a_fname = "Yes", a_lname = "Only 17 left in stock - order soon." WHERE a_id = 466;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 467;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 468;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 469;
update author set a_fname = "No", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 470;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 471;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 472;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 473;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 474;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 475;
update author set a_fname = "No", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 476;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 477;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 478;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 479;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 480;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 481;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 482;
update author set a_fname = "Yes", a_lname = "Only 9 left in stock - order soon." WHERE a_id = 483;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 484;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 485;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 486;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 487;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 488;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 489;
update author set a_fname = "No", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 490;
update author set a_fname = "No", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 491;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 492;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 493;
update author set a_fname = "Yes", a_lname = "Only 15 left in stock - order soon." WHERE a_id = 494;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 495;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 496;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 497;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 498;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 499;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 500;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 501;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 502;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 503;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 504;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 505;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 506;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 507;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 508;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 509;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 510;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 511;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 512;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 513;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 514;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 515;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 516;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 517;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 518;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 519;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 520;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 521;
update author set a_fname = "No", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 522;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 523;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 524;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 525;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 526;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 527;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 528;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 529;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 530;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 531;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 532;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 533;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 534;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 535;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 536;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 537;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 538;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 539;
update author set a_fname = "Yes", a_lname = "Only 17 left in stock - order soon." WHERE a_id = 540;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 541;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 542;
update author set a_fname = "Yes", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 543;
update author set a_fname = "Yes", a_lname = "Only 17 left in stock - order soon." WHERE a_id = 544;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 545;
update author set a_fname = "Yes", a_lname = "Only 12 left in stock - order soon." WHERE a_id = 546;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 547;
update author set a_fname = "No", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 548;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 549;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 550;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 551;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 552;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 553;
update author set a_fname = "No", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 554;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 555;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 556;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 557;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 558;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 559;
update author set a_fname = "Yes", a_lname = "Only 16 left in stock - order soon." WHERE a_id = 560;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 561;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 562;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 563;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 564;
update author set a_fname = "No", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 565;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 566;
update author set a_fname = "Yes", a_lname = "Only 9 left in stock - order soon." WHERE a_id = 567;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 568;
update author set a_fname = "No", a_lname = "Only 12 left in stock - order soon." WHERE a_id = 569;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 570;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 571;
update author set a_fname = "Yes", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 572;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 573;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 574;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 575;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 576;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 577;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 578;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 579;
update author set a_fname = "Yes", a_lname = "Only 17 left in stock - order soon." WHERE a_id = 580;
update author set a_fname = "Yes", a_lname = "Only 16 left in stock - order soon." WHERE a_id = 581;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 582;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 583;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 584;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 585;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 586;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 587;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 588;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 589;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 590;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 591;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 592;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 593;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 594;
update author set a_fname = "Yes", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 595;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 596;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 597;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 598;
update author set a_fname = "No", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 599;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 600;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 601;
update author set a_fname = "Yes", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 602;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 603;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 604;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 605;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 606;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 607;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 608;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 609;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 610;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 611;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 612;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 613;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 614;
update author set a_fname = "Yes", a_lname = "Only 19 left in stock - order soon." WHERE a_id = 615;
update author set a_fname = "Yes", a_lname = "Only 17 left in stock - order soon." WHERE a_id = 616;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 617;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 618;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 619;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 620;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 621;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 622;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 623;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 624;
update author set a_fname = "Yes", a_lname = "Only 16 left in stock - order soon." WHERE a_id = 625;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 626;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 627;
update author set a_fname = "No", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 628;
update author set a_fname = "No", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 629;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 630;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 631;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 632;
update author set a_fname = "No", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 633;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 634;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 635;
update author set a_fname = "Yes", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 636;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 637;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 638;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 639;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 640;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 641;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 642;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 643;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 644;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 645;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 646;
update author set a_fname = "Yes", a_lname = "Only 15 left in stock - order soon." WHERE a_id = 647;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 648;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 649;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 650;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 651;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 652;
update author set a_fname = "Yes", a_lname = "Only 17 left in stock - order soon." WHERE a_id = 653;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 654;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 655;
update author set a_fname = "Yes", a_lname = "Only 12 left in stock - order soon." WHERE a_id = 656;
update author set a_fname = "No", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 657;
update author set a_fname = "Yes", a_lname = "Only 16 left in stock - order soon." WHERE a_id = 658;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 659;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 660;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 661;
update author set a_fname = "Yes", a_lname = "Only 16 left in stock - order soon." WHERE a_id = 662;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 663;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 664;
update author set a_fname = "No", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 665;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 666;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 667;
update author set a_fname = "Yes", a_lname = "Only 12 left in stock - order soon." WHERE a_id = 668;
update author set a_fname = "No", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 669;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 670;
update author set a_fname = "Yes", a_lname = "Only 13 left in stock - order soon." WHERE a_id = 671;
update author set a_fname = "No", a_lname = "Only 12 left in stock - order soon." WHERE a_id = 672;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 673;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 674;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 675;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 676;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 677;
update author set a_fname = "No", a_lname = "Only 12 left in stock - order soon." WHERE a_id = 678;
update author set a_fname = "No", a_lname = "Only 13 left in stock - order soon." WHERE a_id = 679;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 680;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 681;
update author set a_fname = "Yes", a_lname = "Only 16 left in stock - order soon." WHERE a_id = 682;
update author set a_fname = "Yes", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 683;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 684;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 685;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 686;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 687;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 688;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 689;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 690;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 691;
update author set a_fname = "No", a_lname = "Only 16 left in stock - order soon." WHERE a_id = 692;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 693;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 694;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 695;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 696;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 697;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 698;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 699;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 700;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 701;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 702;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 703;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 704;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 705;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 706;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 707;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 708;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 709;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 710;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 711;
update author set a_fname = "No", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 712;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 713;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 714;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 715;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 716;
update author set a_fname = "Yes", a_lname = "Only 15 left in stock - order soon." WHERE a_id = 717;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 718;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 719;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 720;
update author set a_fname = "No", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 721;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 722;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 723;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 724;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 725;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 726;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 727;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 728;
update author set a_fname = "Yes", a_lname = "Only 19 left in stock - order soon." WHERE a_id = 729;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 730;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 731;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 732;
update author set a_fname = "No", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 733;
update author set a_fname = "Yes", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 734;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 735;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 736;
update author set a_fname = "Yes", a_lname = "Only 15 left in stock - order soon." WHERE a_id = 737;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 738;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 739;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 740;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 741;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 742;
update author set a_fname = "Yes", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 743;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 744;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 745;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 746;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 747;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 748;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 749;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 750;
update author set a_fname = "Yes", a_lname = "Only 17 left in stock - order soon." WHERE a_id = 751;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 752;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 753;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 754;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 755;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 756;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 757;
update author set a_fname = "Yes", a_lname = "Only 8 left in stock - order soon." WHERE a_id = 758;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 759;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 760;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 761;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 762;
update author set a_fname = "Yes", a_lname = "Only 13 left in stock - order soon." WHERE a_id = 763;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 764;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 765;
update author set a_fname = "No", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 766;
update author set a_fname = "Yes", a_lname = "Only 13 left in stock - order soon." WHERE a_id = 767;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 768;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 769;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 770;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 771;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 772;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 773;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 774;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 775;
update author set a_fname = "No", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 776;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 777;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 778;
update author set a_fname = "No", a_lname = "Only 13 left in stock - order soon." WHERE a_id = 779;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 780;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 781;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 782;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 783;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 784;
update author set a_fname = "No", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 785;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 786;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 787;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 788;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 789;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 790;
update author set a_fname = "No", a_lname = "Only 12 left in stock - order soon." WHERE a_id = 791;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 792;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 793;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 794;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 795;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 796;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 797;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 798;
update author set a_fname = "No", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 799;
update author set a_fname = "Yes", a_lname = "Only 12 left in stock - order soon." WHERE a_id = 800;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 801;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 802;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 803;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 804;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 805;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 806;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 807;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 808;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 809;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 810;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 811;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 812;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 813;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 814;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 815;
update author set a_fname = "No", a_lname = "Only 19 left in stock - order soon." WHERE a_id = 816;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 817;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 818;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 819;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 820;
update author set a_fname = "No", a_lname = "Only 13 left in stock - order soon." WHERE a_id = 821;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 822;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 823;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 824;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 825;
update author set a_fname = "Yes", a_lname = "Only 9 left in stock - order soon." WHERE a_id = 826;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 827;
update author set a_fname = "Yes", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 828;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 829;
update author set a_fname = "No", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 830;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 831;
update author set a_fname = "Yes", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 832;
update author set a_fname = "Yes", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 833;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 834;
update author set a_fname = "Yes", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 835;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 836;
update author set a_fname = "No", a_lname = "Only 14 left in stock - order soon." WHERE a_id = 837;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 838;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 839;
update author set a_fname = "No", a_lname = "Only 12 left in stock - order soon." WHERE a_id = 840;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 841;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 842;
update author set a_fname = "No", a_lname = "Only 17 left in stock - order soon." WHERE a_id = 843;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 844;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 845;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 846;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 847;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 848;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 849;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 850;
update author set a_fname = "No", a_lname = "Only 9 left in stock - order soon." WHERE a_id = 851;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 852;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 853;
update author set a_fname = "No", a_lname = "Only 20 left in stock - order soon." WHERE a_id = 854;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 855;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 856;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 857;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 858;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 859;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 860;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 861;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 862;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 863;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 864;
update author set a_fname = "Yes", a_lname = "Only 16 left in stock - order soon." WHERE a_id = 865;
update author set a_fname = "No", a_lname = "Only 4 left in stock - order soon." WHERE a_id = 866;
update author set a_fname = "No", a_lname = "Only 16 left in stock - order soon." WHERE a_id = 867;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 868;
update author set a_fname = "Yes", a_lname = "Only 19 left in stock - order soon." WHERE a_id = 869;
update author set a_fname = "Yes", a_lname = "Only 13 left in stock - order soon." WHERE a_id = 870;
update author set a_fname = "Yes", a_lname = "Only 13 left in stock - order soon." WHERE a_id = 871;
update author set a_fname = "Yes", a_lname = "Only 5 left in stock - order soon." WHERE a_id = 872;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 873;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 874;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 875;
update author set a_fname = "Yes", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 876;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 877;
update author set a_fname = "Yes", a_lname = "Only 10 left in stock - order soon." WHERE a_id = 878;
update author set a_fname = "Yes", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 879;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 880;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 881;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 882;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 883;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 884;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 885;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 886;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 887;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 888;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 889;
update author set a_fname = "No", a_lname = "Only 11 left in stock - order soon." WHERE a_id = 890;
update author set a_fname = "No", a_lname = "Only 18 left in stock - order soon." WHERE a_id = 891;
update author set a_fname = "Yes", a_lname = "Only 6 left in stock - order soon." WHERE a_id = 892;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 893;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 894;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 895;
update author set a_fname = "No", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 896;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 897;
update author set a_fname = "Yes", a_lname = "Only 9 left in stock - order soon." WHERE a_id = 898;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 899;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 900;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 901;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 902;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 903;
update author set a_fname = "No", a_lname = "Only 7 left in stock - order soon." WHERE a_id = 904;
update author set a_fname = "Yes", a_lname = "Only 1 left in stock - order soon." WHERE a_id = 905;
update author set a_fname = "Yes", a_lname = "Only 3 left in stock - order soon." WHERE a_id = 906;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 907;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 908;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 909;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 910;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 911;
update author set a_fname = "No", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 912;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 913;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 914;
update author set a_fname = "Yes", a_lname = "In stock" WHERE a_id = 915;
update author set a_fname = "No", a_lname = "In stock" WHERE a_id = 916;
update author set a_fname = "No", a_lname = "Only 2 left in stock - order soon." WHERE a_id = 917;
